Trix.config.lang =
  bold: "Lihavointi"
  bullets: "Luettelomerkit"
  byte:  "Tavu"
  bytes: "Tavut"
  captionPlaceholder: "Kirjoita teksti tähän"
  captionPrompt: "Lisää teksti"
  code: "Koodi"
  heading1: "Otsikko"
  indent: "Sisennä"
  italic: "Kursiivi"
  link: "Linkki"
  numbers: "Numerointi"
  outdent: "Vähennä sisennystä"
  quote: "Lainaus"
  redo: "Tee uudelleen"
  remove: "Poista"
  strike: "Yliviivaus"
  underline: "Alleviivaus"
  undo: "Kumoa"
  unlink: "Poista linkkaus"
  urlPlaceholder: "Kirjoita osoite"
  GB: "Gt"
  KB: "Kt"
  MB: "Mt"
  PB: "Pt"
  TB: "Tt"
